global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "climatrak-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: "climatrak-worker"
    static_configs:
      - targets: ["worker:9187"]
